services:
  - type: web
    name: ai-powered-legal-assistant
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port=$PORT --server.address=0.0.0.0"
    runtime: python-3.10.14
